api_platform:
    title: SSA-API
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        # Préfixe des routes
        route_prefix: '/api'
    eager_loading:
        max_joins: 5
        force_eager: false
