<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250829110359 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Création des tables pour les entités Agent, Country et Mission';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_name VARCHAR(255) NOT NULL, enrolement_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, infiltrated_country_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_268B9C9D9FB86183 ON agent (infiltrated_country_id)');
        $this->addSql('CREATE TABLE agent_mission (agent_id INT NOT NULL, mission_id INT NOT NULL, PRIMARY KEY(agent_id, mission_id))');
        $this->addSql('CREATE INDEX IDX_423490963414710B ON agent_mission (agent_id)');
        $this->addSql('CREATE INDEX IDX_42349096BE6CAE90 ON agent_mission (mission_id)');
        $this->addSql('CREATE TABLE country (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, cell_leader_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5373C966984E18B1 ON country (cell_leader_id)');
        $this->addSql('CREATE TABLE mission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, danger VARCHAR(255) NOT NULL, status VARCHAR(255) DEFAULT NULL, description TEXT NOT NULL, objectives TEXT NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, country_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9067F23CF92F3E70 ON mission (country_id)');
        $this->addSql('ALTER TABLE agent ADD CONSTRAINT FK_268B9C9D9FB86183 FOREIGN KEY (infiltrated_country_id) REFERENCES country (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_mission ADD CONSTRAINT FK_423490963414710B FOREIGN KEY (agent_id) REFERENCES agent (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_mission ADD CONSTRAINT FK_42349096BE6CAE90 FOREIGN KEY (mission_id) REFERENCES mission (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966984E18B1 FOREIGN KEY (cell_leader_id) REFERENCES agent (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mission ADD CONSTRAINT FK_9067F23CF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent DROP CONSTRAINT FK_268B9C9D9FB86183');
        $this->addSql('ALTER TABLE agent_mission DROP CONSTRAINT FK_423490963414710B');
        $this->addSql('ALTER TABLE agent_mission DROP CONSTRAINT FK_42349096BE6CAE90');
        $this->addSql('ALTER TABLE country DROP CONSTRAINT FK_5373C966984E18B1');
        $this->addSql('ALTER TABLE mission DROP CONSTRAINT FK_9067F23CF92F3E70');
        $this->addSql('DROP TABLE agent');
        $this->addSql('DROP TABLE agent_mission');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE mission');
    }
}
